const USERS_DB_COLLECTION_NAME = 'users';
const GAME_DB_COLLECTION_NAME = 'games';
const ORDER_DB_COLLECTION_NAME = 'orders';
const METADATA_DB_COLLECTION_NAME = 'metadata';

export {
  USERS_DB_COLLECTION_NAME,
  GAME_DB_COLLECTION_NAME,
  ORDER_DB_COLLECTION_NAME,
  METADATA_DB_COLLECTION_NAME,
};
